// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quanlibanvetau1.context;

#nullable disable

namespace quanlibanvetau2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250705131205_abc")]
    partial class abc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("quanlibanvetau.model.ChuyenTau", b =>
                {
                    b.Property<int>("MaChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyen"));

                    b.Property<string>("GaDen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GaDi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaVe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenTau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianDen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongSoGhe")
                        .HasColumnType("int");

                    b.HasKey("MaChuyen");

                    b.ToTable("ChuyenTaus");

                    b.HasData(
                        new
                        {
                            MaChuyen = 1,
                            GaDen = "Sài Gòn",
                            GaDi = "Hà Nội",
                            GiaVe = 100000m,
                            TenTau = "SE1",
                            ThoiGianDen = new DateTime(2025, 7, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKhoiHanh = new DateTime(2025, 7, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            TongSoGhe = 100
                        },
                        new
                        {
                            MaChuyen = 2,
                            GaDen = "Nha Trang",
                            GaDi = "Đà Nẵng",
                            GiaVe = 300000m,
                            TenTau = "SE2",
                            ThoiGianDen = new DateTime(2025, 7, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKhoiHanh = new DateTime(2025, 7, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TongSoGhe = 80
                        },
                        new
                        {
                            MaChuyen = 3,
                            GaDen = "Sài Gòn",
                            GaDi = "Huế",
                            GiaVe = 400000m,
                            TenTau = "SE3",
                            ThoiGianDen = new DateTime(2025, 7, 6, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKhoiHanh = new DateTime(2025, 7, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TongSoGhe = 120
                        });
                });

            modelBuilder.Entity("quanlibanvetau.model.HanhKhach", b =>
                {
                    b.Property<int>("MaHanhKhach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHanhKhach"));

                    b.Property<int>("CMND")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHanhKhach");

                    b.ToTable("HanhKhaches");

                    b.HasData(
                        new
                        {
                            MaHanhKhach = 1,
                            CMND = 123456789,
                            DiaChi = "Hà Nội",
                            DienThoai = "0911000111",
                            HoTen = "Phạm Thị D"
                        },
                        new
                        {
                            MaHanhKhach = 2,
                            CMND = 234567890,
                            DiaChi = "Đà Nẵng",
                            DienThoai = "0922000222",
                            HoTen = "Ngô Văn E"
                        },
                        new
                        {
                            MaHanhKhach = 3,
                            CMND = 345678901,
                            DiaChi = "HCM",
                            DienThoai = "0933000333",
                            HoTen = "Đỗ Thị F"
                        });
                });

            modelBuilder.Entity("quanlibanvetau.model.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            MaNV = 1,
                            SoDienThoai = "0909123456",
                            TenNV = "Nguyễn Văn A"
                        },
                        new
                        {
                            MaNV = 2,
                            SoDienThoai = "0988777666",
                            TenNV = "Trần Thị B"
                        },
                        new
                        {
                            MaNV = 3,
                            SoDienThoai = "0933555777",
                            TenNV = "Lê Văn C"
                        });
                });

            modelBuilder.Entity("quanlibanvetau.model.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MaHanhKhach")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("MaHanhKhach");

                    b.HasIndex("MaNV");

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            TenDangNhap = "admin",
                            MaNV = 1,
                            MatKhau = "123",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            TenDangNhap = "nhanvien",
                            MaNV = 2,
                            MatKhau = "abc",
                            VaiTro = "NhanVien"
                        },
                        new
                        {
                            TenDangNhap = "khach",
                            MaHanhKhach = 1,
                            MatKhau = "xyz",
                            VaiTro = "KhachHang"
                        });
                });

            modelBuilder.Entity("quanlibanvetau.model.ThongKe", b =>
                {
                    b.Property<int>("MaThongKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongKe"));

                    b.Property<decimal>("DoanhThu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaChuyen")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongVeDaBan")
                        .HasColumnType("int");

                    b.HasKey("MaThongKe");

                    b.HasIndex("MaChuyen");

                    b.HasIndex("MaNV");

                    b.ToTable("ThongKes");

                    b.HasData(
                        new
                        {
                            MaThongKe = 1,
                            DoanhThu = 500000m,
                            MaChuyen = 1,
                            MaNV = 1,
                            Ngay = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongVeDaBan = 1
                        },
                        new
                        {
                            MaThongKe = 2,
                            DoanhThu = 450000m,
                            MaChuyen = 2,
                            MaNV = 2,
                            Ngay = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongVeDaBan = 1
                        },
                        new
                        {
                            MaThongKe = 3,
                            DoanhThu = 600000m,
                            MaChuyen = 3,
                            MaNV = 3,
                            Ngay = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongVeDaBan = 1
                        });
                });

            modelBuilder.Entity("quanlibanvetau.model.VeTau", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVe"));

                    b.Property<decimal>("GiaVe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaChuyen")
                        .HasColumnType("int");

                    b.Property<int?>("MaHanhKhach")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVe");

                    b.HasIndex("MaChuyen");

                    b.HasIndex("MaHanhKhach");

                    b.HasIndex("MaNV");

                    b.ToTable("VeTaus");

                    b.HasData(
                        new
                        {
                            MaVe = 1,
                            GiaVe = 0m,
                            MaChuyen = 1,
                            MaHanhKhach = 1,
                            MaNV = 1,
                            NgayDat = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoGhe = "A01",
                            TrangThai = "DaDat"
                        },
                        new
                        {
                            MaVe = 2,
                            GiaVe = 0m,
                            MaChuyen = 2,
                            MaHanhKhach = 2,
                            MaNV = 2,
                            NgayDat = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoGhe = "B02",
                            TrangThai = "DaDat"
                        },
                        new
                        {
                            MaVe = 3,
                            GiaVe = 0m,
                            MaChuyen = 3,
                            MaHanhKhach = 3,
                            MaNV = 3,
                            NgayDat = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoGhe = "C03",
                            TrangThai = "DaDat"
                        });
                });

            modelBuilder.Entity("quanlibanvetau.model.TaiKhoan", b =>
                {
                    b.HasOne("quanlibanvetau.model.HanhKhach", "HanhKhach")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaHanhKhach");

                    b.HasOne("quanlibanvetau.model.NhanVien", "NhanVien")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaNV");

                    b.Navigation("HanhKhach");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("quanlibanvetau.model.ThongKe", b =>
                {
                    b.HasOne("quanlibanvetau.model.ChuyenTau", "ChuyenTau")
                        .WithMany("ThongKes")
                        .HasForeignKey("MaChuyen");

                    b.HasOne("quanlibanvetau.model.NhanVien", "NhanVien")
                        .WithMany("ThongKes")
                        .HasForeignKey("MaNV");

                    b.Navigation("ChuyenTau");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("quanlibanvetau.model.VeTau", b =>
                {
                    b.HasOne("quanlibanvetau.model.ChuyenTau", "ChuyenTau")
                        .WithMany("VeTaus")
                        .HasForeignKey("MaChuyen");

                    b.HasOne("quanlibanvetau.model.HanhKhach", "HanhKhach")
                        .WithMany("VeTaus")
                        .HasForeignKey("MaHanhKhach");

                    b.HasOne("quanlibanvetau.model.NhanVien", "NhanVien")
                        .WithMany("VeTaus")
                        .HasForeignKey("MaNV");

                    b.Navigation("ChuyenTau");

                    b.Navigation("HanhKhach");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("quanlibanvetau.model.ChuyenTau", b =>
                {
                    b.Navigation("ThongKes");

                    b.Navigation("VeTaus");
                });

            modelBuilder.Entity("quanlibanvetau.model.HanhKhach", b =>
                {
                    b.Navigation("TaiKhoans");

                    b.Navigation("VeTaus");
                });

            modelBuilder.Entity("quanlibanvetau.model.NhanVien", b =>
                {
                    b.Navigation("TaiKhoans");

                    b.Navigation("ThongKes");

                    b.Navigation("VeTaus");
                });
#pragma warning restore 612, 618
        }
    }
}
